spring:
  application:
    name: mini-autorizador-camada
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/miniautorizador}
    username: root
    password:

  security:
    user:
      name: username
      password: password
      roles: USER